os: osx
osx_image: xcode11
sudo: false
language: objective-c

env:
  - SDK="iphoneos13.0"

script:
  - xcodebuild clean build -sdk $SDK -configuration Debug CODE_SIGN_IDENTITY=\"\" CODE_SIGNING_REQUIRED=NO

before_install:
  - xcodebuild -showsdks
